# 2D facing indexing

In [1]:
import numpy as np

clase_id_edad = np.array([[1, 22],
                            [2, 21],
                            [3, 27],
                            [4, 26]] )

print(clase_id_edad)

print(clase_id_edad.shape)

print(clase_id_edad[:, 1] % 2 == 0)

# print(clase_id_edad[clase_id_edad[:, 1] % 2 == 0])
print(clase_id_edad[:, 0][clase_id_edad[:, 1] % 2 == 0])

[[ 1 22]
 [ 2 21]
 [ 3 27]
 [ 4 26]]
(4, 2)
[ True False False  True]
[1 4]


# Fancy indexing vs. np.where()

In [3]:
ar = np.where( clase_id_edad[:, 1] % 2 == 0 )
print(ar)


(array([0, 3]),)


# Filtrado con np.where()

In [14]:


print(np.where(clase_id_edad[:,1] % 2 == 0))




(array([0, 3]),)


# Obtención de elementos con np.where()

In [ ]:
array_2 = np.array([[0,0,4,3,0,0,2,0,9],
                    [0,0,5,0,0,9,0,0,1],
                    [0,7,0,0,6,0,0,4,3],
                    [0,0,6,0,0,2,0,8,7],
                    [1,9,0,0,0,7,4,0,0],
                    [0,5,0,0,8,3,0,0,0],
                    [6,0,0,0,0,0,1,0,5],
                    [0,0,3,5,0,8,6,9,9],
                    [0,4,2,9,1,0,3,0,0]])

row_ind, column_ind = np.where(array_2 == 0)

print(row_ind)
print(column_ind)

# Encontrar y reemplazar

In [13]:
resul = np.where(array_2 == 0, -1, array_2)
print(resul)


[[-1 -1  4  3 -1 -1  2 -1  9]
 [-1 -1  5 -1 -1  9 -1 -1  1]
 [-1  7 -1 -1  6 -1 -1  4  3]
 [-1 -1  6 -1 -1  2 -1  8  7]
 [ 1  9 -1 -1 -1  7  4 -1 -1]
 [-1  5 -1 -1  8  3 -1 -1 -1]
 [ 6 -1 -1 -1 -1 -1  1 -1  5]
 [-1 -1  3  5 -1  8  6  9  9]
 [-1  4  2  9  1 -1  3 -1 -1]]


# Añadiendo y removiendo datos: Concatenación y Compatibilidad con shap

In [18]:
array1 = np.array([[18,12,3], [6,7,8],[11,15,13]])
array2 = np.array([[7,1], [23,28],[4,11]])

print(np.concatenate((array1, array2), axis=1))

# print(array1 + array2) # No funciona porque no son del mismo tamaño

# print(np.concatenate((array1, array2), axis=0)) # No funciona porque no son del mismo tamaño

                 

[[18 12  3  7  1]
 [ 6  7  8 23 28]
 [11 15 13  4 11]]


In [22]:
classroom_ids_and_sizes = np.array([[1,22],[2, 21],[3, 27],[4,26]] )
new_classrooms = np.array([[5, 30],[5,17]] )

# , axis=0 : np.concatenate(): Concatena a lo largo del primer eje por defecto.
print(np.concatenate((classroom_ids_and_sizes,new_classrooms))) 


[[ 1 22]
 [ 2 21]
 [ 3 27]
 [ 4 26]
 [ 5 30]
 [ 5 17]]


# Borrar con np.delete()

In [29]:
data_clases = np.array([[1, 22, 1, 'James'],
                            [2, 21, 1, 'Geoge'],   
                            [3, 27, 3, 'Amy'],
                            [4, 26, 3, 'Meehir']] )

print(data_clases)

# Borrando filas
delete_axis_y = np.delete(data_clases, 1, axis=0)
print(delete_axis_y)

# Borrando columnas
delete_axis_x = np.delete(data_clases, 1, axis=1)
print(delete_axis_x)


[['1' '22' '1' 'James']
 ['2' '21' '1' 'Geoge']
 ['3' '27' '3' 'Amy']
 ['4' '26' '3' 'Meehir']]
[['1' '22' '1' 'James']
 ['3' '27' '3' 'Amy']
 ['4' '26' '3' 'Meehir']]
[['1' '1' 'James']
 ['2' '1' 'Geoge']
 ['3' '3' 'Amy']
 ['4' '3' 'Meehir']]


# Borrar sin especificar el eje

In [31]:

delete_data_clases = np.delete(data_clases, 1)
print(data_clases) 
print(delete_data_clases) 


[['1' '22' '1' 'James']
 ['2' '21' '1' 'Geoge']
 ['3' '27' '3' 'Amy']
 ['4' '26' '3' 'Meehir']]
['1' '1' 'James' '2' '21' '1' 'Geoge' '3' '27' '3' 'Amy' '4' '26' '3'
 'Meehir']
